easy_admin:
    site_name: '<img src="https://pm1.narvii.com/6885/5d96c3a9a9b487cbbcdcbb5049f2040d70114fc4r1-677-616v2_128.jpg" /> E CORP'
    entities:
        Category:
          class: App\Entity\Category
          new:
            title: 'Add New Category'
          edit:
            title: 'Edit Category'
        Comment:
          class: App\Entity\Comment
          new:
            title: 'Add New Comment'
          edit:
            title: 'Edit Comment'
        County:
          class: App\Entity\County
          new:
            title: 'Add New County'
          edit:
            title: 'Edit County'
        State:
          class: App\Entity\State
          new:
            title: 'Add New State'
          edit:
            title: 'Edit State'
        Traobject:
          class: App\Entity\Traobject
          list:
            fields:
              - { property: 'id', type: 'int' }
              - { property: 'title', type: 'text' }
              - { property: 'picture', type: 'image', base_path: '%app.path.uploads_dir%' }
              - { property: 'event_at', type: 'datetime' }
              - { property: 'city', type: 'text' }

          show:
            fields:
              - { property: 'picture', type: 'image', base_path: '%app.path.uploads_dir%' }
          form:
            fields:
              - { property: 'title', type: 'text' }
              - { property: 'pictureFile', type: 'vich_image' }
              - { property: 'event_at', type: 'datetime' }
              - { property: 'city', type: 'text' }
          new:
            title: 'Add New Traobject'
          edit:
            title: 'Edit Traobject'
        User:
          class: App\Entity\User
          list:
            fields:
              - { property: 'id', type: 'int' }
              - { property: 'firstname', type: 'text' }
              - { property: 'lastname', type: 'text' }
              - { property: 'email', type: 'email' }
              - { property: 'phone', type: 'phone' }
              - { property: 'picture', type: 'image', base_path: '%app.path.uploads_dir%' }
          show:
            fields:
              - { property: 'picture', type: 'image', base_path: '%app.path.uploads_dir%' }
          form:
            fields:
              - { property: 'firstname', type: 'text' }
              - { property: 'lastname', type: 'text' }
              - { property: 'phone', type: 'text' }
              - { property: 'email', type: 'email' }
              - { property: 'pictureFile', type: 'vich_image' }
    design:
      assets:
        favicon: 'assets/images/favicon.png'
        css:
          - 'bundles/easyadmin/bootstrap-all.css'
        js:
          - 'bundles/easyadmin/bootstrap-all.js'
      brand_color : '#000d1a'