easy_admin:
    site_name: '<img src="https://pm1.narvii.com/6885/5d96c3a9a9b487cbbcdcbb5049f2040d70114fc4r1-677-616v2_128.jpg" /> E CORP'
    entities:
        Category:
          class: App\Entity\Category
          new:
            title: 'Add New Category'
          edit:
            title: 'Edit Category'
        Comment:
          class: App\Entity\Comment
          new:
            title: 'Add New Comment'
          edit:
            title: 'Edit Comment'
        County:
          class: App\Entity\County
          new:
            title: 'Add New County'
          edit:
            title: 'Edit County'
        State:
          class: App\Entity\State
          new:
            title: 'Add New State'
          edit:
            title: 'Edit State'
        Traobject:
          class: App\Entity\Traobject
          new:
            title: 'Add New Traobject'
          edit:
            title: 'Edit Traobject'
        User:
          class: App\Entity\User
          new:
            title: 'Add New User'
          edit:
            title: 'Edit User'
    design:
      assets:
        favicon: 'assets/images/favicon.png'
        css:
          - 'bundles/easyadmin/bootstrap-all.css'
        js:
          - 'bundles/easyadmin/bootstrap-all.js'
      brand_color : '#000d1a'