easy_admin:
    site_name: 'TRAOUVE'
    entities:
        Category:
          class: App\Entity\Category
          label: 'Catégorie'
          list:
            title: 'Liste des catégories'
          new:
            title: 'Ajouter une nouvelle catégorie'
          edit:
            title: 'Modifier une nouvelle catégorie'
        Comment:
          class: App\Entity\Comment
          label: 'Commentaire'
          list:
            title: 'Liste des commentaires'
          new:
            title: 'Ajouter un nouveau commentaire'
          edit:
            title: 'Modifier un commentaire'
        County:
          class: App\Entity\County
          label: 'Département'
          list:
            title: 'Liste des départements'
          new:
            title: 'Ajouter un nouveau département'
          edit:
            title: 'Modifier un département'
        State:
          class: App\Entity\State
          label: 'Statut'
          list:
            title: 'Liste des statuts'
          new:
            title: 'Ajouter un nouveau statut'
          edit:
            title: 'Modifier un statut'
        Traobject:
          class: App\Entity\Traobject
          label: 'Objet'
          list:
            title: 'Liste des objets'
            fields:
              - { property: 'id', type: 'int' }
              - { property: 'title', type: 'text' }
              - { property: 'picture', type: 'image', base_path: '%app.path.uploads_dir%' }
              - { property: 'event_at', type: 'datetime' }
              - { property: 'city', type: 'text' }
              - { property: 'category', type: 'text' }
              - { property: 'county', type: 'text' }

          show:
            fields:
              - { property: 'picture', type: 'image', base_path: '%app.path.uploads_dir%' }
          form:
            fields:
              - { property: 'title', type: 'text' }
              - { property: 'state', type: 'text' }
              - { property: 'category', type_options: { expanded: false }}
              - { property: 'description', type: 'text' }
              - { property: 'pictureFile', type: 'vich_image' }
              - { property: 'event_at', type: 'date' }
              - { property: 'city', type: 'text' }
              - { property: 'address', type: 'text' }
              - { property: 'county', type_options: { expanded: false }}
          new:
            title: 'Ajouter un objet'
          edit:
            title: 'Modifier un objet'
        User:
          class: App\Entity\User
          label: 'Utilisateurs'
          list:
            title: 'Liste des utilisateurs'
            fields:
              - { property: 'id', type: 'int' }
              - { property: 'firstname', type: 'text' }
              - { property: 'lastname', type: 'text' }
              - { property: 'email', type: 'email' }
              - { property: 'phone', type: 'text' }
              - { property: 'picture', type: 'image', base_path: '%app.path.uploads_dir%' }
          show:
            fields:
              - { property: 'picture', type: 'image', base_path: '%app.path.uploads_dir%' }
          form:
            fields:
              - { property: 'firstname', type: 'text' }
              - { property: 'lastname', type: 'text' }
              - { property: 'phone', type: 'text' }
              - { property: 'email', type: 'email' }
              - { property: 'pictureFile', type: 'vich_image' }
    design:
      assets:
        favicon: 'assets/images/favicon.png'
        css:
          - 'bundles/easyadmin/bootstrap-all.css'
        js:
          - 'bundles/easyadmin/bootstrap-all.js'
      brand_color : '#eb6864'